### PR TITLE
Batch of fixes 20141231

### PR DESCRIPTION
**Pull request by aarononeal**
The last commit is dependent on some of the former so I'm batching all these together. I added detailed descriptions to each commit to make review easier.

Two of the more significant issues fixed include binary string truncation and blob support.

### CODE REVIEW

**Comment by brodybits** [comment]
Happy New Year! Many thanks for your efforts to fix the support for Base64,
return types, and other issues. I am going on a short vacation and will
look into integrating the fixes sometime next week.

I do really like the cleanup of the Base64 code. I suspect it triggers a
dependency on a more recent version of Cordova and will label it, and
describe a workaround for those who are using an older version of Cordova.

I am also wondering what will happen if we try the Base64 on WP8. If it
doesn't work we can simply skip the Base64 test on WP8.

Chris

On Thursday, January 1, 2015, Aaron Oneal <notifications@github.com> wrote:

> The last commit is dependent on some of the former so I'm batching all
> these together. I added detailed descriptions to each commit to make review
> easier.
>
> Two of the more significant issues fixed include binary string truncation
> and blob support.
> ------------------------------
> You can merge this Pull Request by running
>
>   git pull https://github.com/spicypixel/cordova-plugin-websql hotfix/batch-20141231
>
> Or view, comment on, or merge it at:
>
>   https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170
> Commit Summary
>
>    - Fix test runner to use correct plugin id.
>    - Fix database close and reopen test.
>    - Propagate statement failures to transaction failures.
>    - Fix error types on open, close, and deleteDb.
>    - Fix transaction and statement errors to conform to SQLError.
>    - Fix to prevent double marshaling of data.
>    - Fix iOS regex args check.
>    - Fix truncation in iOS query result string encoding.
>    - Fix warning regarding test runner viewport format.
>    - Support SQL blob marshaling using ArrayBuffer and Base64.
>
> File Changes
>
>    - *M* SQLitePlugin.coffee.md
>    <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170/files#diff-0>
>    (173)
>    - *M* bin/test.sh
>    <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170/files#diff-1>
>    (2)
>    - *M* src/android/org/pgsqlite/SQLitePlugin.java
>    <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170/files#diff-2>
>    (4)
>    - *M* src/ios/SQLitePlugin.h
>    <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170/files#diff-3>
>    (8)
>    - *M* src/ios/SQLitePlugin.m
>    <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170/files#diff-4>
>    (232)
>    - *M* test-www/www/index.html
>    <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170/files#diff-5>
>    (232)
>
> Patch Links:
>
>    - https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170.patch
>    - https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brodysoft/Cordova-SQLitePlugin/pull/170>.
>


-- 
Sent from my mobile

**Comment by aarononeal** [comment]
Happy New Year! :-)

It looks like the NSData+Base64 files have been around in one shape or another [since early 2012](https://github.com/apache/cordova-ios/commits/master/CordovaLib/Classes/NSData%2BBase64.m), but I only tested against the latest Cordova build.

On WP8, what I expect will happen is the ArrayBuffer will encode to a new `sqlblob` URI and get serialized by the "native" side as text because it doesn't have logic yet to recognize the prefix. When read back, the `sqlblob` will just read as text and the JS side will be able to decode it. So, the new tests should pass and the only real difference will be that the backing data will be stored as a string instead of binary. Still unsupported in WP8 is the ability to read a binary blob from an externally created database back as anything other than text. We need to have it return a `sqlblob` in those cases like Android and iOS do now. At some point I'll be able to test on WP8.

Also, I made 2 minor updates to the pull tonight. I updated the close commit 8c3bdcc so that the close method verifies it's not in a transaction. This would have avoided the original test bug had it been in place. I also added commit 96d5db8 so that executeSql throws when it's supposed to in order to make it more obvious why the plugin fails when used with ES6 promises.

**Comment by nolanlawson** [comment]
Very cool, and the new tests are highly appreciated.

**Comment by brodybits** [comment]
Thanks @aarononeal, I will include the changes using `git cherry-pick` due to the branching model of this project.

My only major comment is that if you propose more changes in the future, changes to the Javascript need to be included when we change the CoffeeScript for the Cordova CLI installation to work. I will take care of this for the changes that you have already proposed.

**Comment by aarononeal** [comment]
Thanks. I wasn't sure how you wanted to handle integration so I left out the auto-generated JS, but I can definitely include that in the future.

**Comment by brody2consult** [comment]
For general reference: all changes in this PR are included except for the BLOB enhancements. I plan to integrate the blob enhancements with the cordova-sqlite-ext version when I get a chance.

**Pull request closed without merging**
